services:

  registry:
    build:
      context: ./service-registry

    ports:
      - "8761:8761"

  config:
    build:
      context: ./config-server

    ports:
      - "8888:8888"

    depends_on:
      - registry

  gateway:
    build: ./api-gateway

    depends_on:
      registry:
        condition: service_started
      config:
        condition: service_started
      wallet:
        condition: service_started
      transaction:
        condition: service_started

    ports:
      - "8080:8080"

  wallet:
    depends_on:
      config:
        condition: service_started
      registry:
        condition: service_started

  transaction:
    depends_on:
      config:
        condition: service_started
      registry:
        condition: service_started