services:

  registry:
    build: ./service-registry
    container_name: registry

    ports:
      - "8761:8761"

  config:
    build: ./config-server
    container_name: config

    ports:
      - "8888:8888"

    depends_on:
      - registry

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  wallet:
    build: ./wallet-service
    container_name: wallet

    ports:
      - "8081:8080"

    depends_on:
      config:
        condition: service_healthy

  transaction:
    build: ./transaction-service
    container_name: transaction

    ports:
      - "8082:8080"

    depends_on:
      config:
        condition: service_healthy

  gateway:
    build: ./api-gateway
    container_name: gateway

    ports:
      - "8080:8080"

    depends_on:
      config:
        condition: service_healthy
      wallet:
        condition: service_started
      transaction:
        condition: service_started
