server.port=8888

spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/AyushK95/AyushmaanPay-ConfigRepo

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.fail-fast=false
management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true